### ISSUE TITLE
use default export from for `babelJest.createTransformer`

### ISSUE THREAD

**Issue by fmacherey** [linariaplug/craco-linaria3#4]
It looks like with newer versions of jest, you have to use the default export. So changing `babelJest.createTransformer` to `babelJest.default.createTransformer`

See this issue from jest https://github.com/facebook/jest/issues/11444#issuecomment-847909076

**Comment by fmacherey** [comment]
When I use the tests, i get the following message:
```
  ● Test suite failed to run

    TypeError: babelJest.createTransformer is not a function

      at Object.<anonymous> (node_modules/craco-linaria3/src/babelTransform.js:3:28)
      at node_modules/@jest/transform/build/ScriptTransformer.js:382:73
          at Array.map (<anonymous>)

```
